#+TITLE: Org Share development plan

* Backend Overview

  This is my first REST API I've ever made...

** Description

  The end product I'm looking for is to have a website with the following workflow:
  
  - lets users anonymously upload an org-mode notes

  - they also get to choose a theme for the notes from a menu

  - then they receive an IMGUR-style generated link of the generated, themed notes
  
  In order to support this, the REST API should let users POST their document and desired theme, and the browser should retrieve the link to it once it's been generated
	
** Considerations

   
   - Should I allow account creation? Initially I should probably only let me use it through log in
   
   - Maximum filesize: 5k word of lorem ipsum is like 33kbytes. So a 35kbyte limit is reasonable.

   - Should I use emacs for conversion? That's probably stupid. I could convert with Pandoc but there would be some info lost maybe/probably


** Database

   - File is just uploaded to a column in a PostgreSQL table, given autoincrement ID

** Rough API

*** POST File

	POST a file and then URL is returned

** Testing API

*** POST

#+BEGIN_SRC bash

# run the server in another window, then
cd test
curl -k -F "files=@test-org.org" https://localhost:5001/api/orgFiles

#+END_SRC

** Useful links
   
   * [[https://stackoverflow.com/questions/22072773/batch-export-of-org-mode-files-from-the-command-line][Export notes from command line]]
   
   * [[https://github.com/fniessen/org-html-themes][Org themes]]

   * [[https://animesh.blog/ef-core-code-first-with-postgres/][EF code first]]

** Installation

   Later I'll have a more solid installation procedure

   Install `dotnet-sdk-22` and postgres then

#+BEGIN_SRC bash

git clone https://github.com/GabrielDougherty/org-share.git
cd org-share
dotnet restore

#+END_SRC

   Also use the create_tables script to create the tables
